# entrance:
bus_num: 25
random: True                      # if True: random initial state
seed: 19                           # when random is False

# request:
req_order: [0, 1, 2]              # 0: ent, 1: cs, 2: fs
interlock: 0

# Employee:
emp_num: 0  # int/false

# CS:
cs_num: 25

# FS:
fs_num: 2

# time:   time steps = minutes
min_duration: 360                  # min number of time steps between first and last arriving bus
max_duration: 600                # max duration
bus_time: 1                       # number of time steps between two simultaneously arrived buses
charge_time: 120                 # number of time steps needed to charge to the next level
fuel_time: 5                     # number of time steps needed to fuel to the next level
time_delay: 1          # 1 for eval           # number of time steps considered as delay
travel_time: [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
              [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
              [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]
emp_time:   [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
              [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
              [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]  # emp travel from SB to a station

# reward:
inst: 0                                 # 0 for evaluation
fail: -100
win: 100
repeat: 0
repeat_per_action: False

# render fps:
render_reset: 1
render_fast: 100
render_slow: 0.2                # if fail or success

# training:
sb3_model: MPPO                  # MaskablePPO = MPPO
mask: True                      # must be false unless model is MPPO
training: 'training5/'
ent_coef: 0
models_dir: 'models/'
logs_dir: 'logs/'
device: cuda:1
tr_render: False
total_steps: 310          # * ten-thousand steps

# evaluation:
model_path_ev: 'models/training4/MPPO-1691059515/500000'    # model path or name of rule based models
ev_mask: True                                              # must be false unless model is MPPO
results_dir: 'results/'
episode_num: 100
iteration_num: 5
save_graph: False
show_graph: False
ev_render: False
