# entrance:
bus_num: 5
random: False                     # if True: random initial state
seed: 39

# request:
req_order: [2, 1, 0]              # 0: ent, 1: cs, 2:fs

# CS:
cs_num: 5

# FS:
fs_num: 2

# time:
min_duration: 1                   # min number of time steps between first and last arriving bus
max_duration: 7                   # max duration
bus_time: 0                       # number of time steps between two simultaneously arrived buses
charge_time: 3                    # number of time steps needed to charge to next level
fuel_time: 1                      # number of time steps needed to fuel to next level
time_delay: 1                     # number of time steps considered as delay
travel_time:

# reward:
inst: 1
fail: -10
win: 10



